services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .    # The context should be the root of the project
      dockerfile: frontend/Dockerfile   # Specify the Dockerfile explicitly
    ports:
      - "3000:3000"
